# -*- coding: utf-8 -*-
"""Financial News Sentiment [RNN - LSTM - GRU - MiniLM].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/170gLcFcuLqIYpy9Vs47W4V1-C3IxsXag

# Import libraries
"""

!pip install -q torchinfo

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torchinfo import summary

import random
import numpy as np
import pandas as pd
import os
from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    PreTrainedModel,
    PretrainedConfig,
    Trainer,
    TrainingArguments,
    DataCollatorWithPadding,
    PreTrainedTokenizerFast,
    EarlyStoppingCallback,
    pipeline
)
from transformers.modeling_outputs import SequenceClassifierOutput

from tokenizers import Tokenizer, models, trainers, pre_tokenizers

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, precision_recall_fscore_support

from datasets import load_dataset

IGNORE_INDEX = -100
SEED = 42
MAX_RNN_LEN = 128
MAX_BERT_LEN = 512

def set_seed(seed=42):
	random.seed(seed)
	os.environ['PYTHONHASHSEED'] = str(seed)
	np.random.seed(seed)

	torch.manual_seed(seed)

	if torch.backends.mps.is_available():
		torch.mps.manual_seed(seed)
		os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"

	if torch.cuda.is_available():
		torch.cuda.manual_seed(seed)
		torch.cuda.manual_seed_all(seed)
		torch.backends.cudnn.deterministic = True
		torch.backends.cudnn.benchmark = False

	try:
		torch.use_deterministic_algorithms(True)
	except RuntimeError:
		pass

set_seed(SEED)
device = 'cuda' if torch.cuda.is_available() else 'cpu'

"""# Download dataset"""

!gdown 1o09HEkDBBEjsW3gN76vDYfCAKiCqpcpg
!unzip /content/financial_sentiment.zip
!rm -rf /content/financial_sentiment.zip

data_path = '/content/all-data.csv'
headers = ['sentiment', 'content']

df = pd.read_csv(
  data_path,
  names=headers,
  encoding='ISO-8859-1'
)
df

classes_lst = df['sentiment'].unique()
n_classes = len(classes_lst)
classes_lst

label2id = {
    class_name: idx
    for idx, class_name in enumerate(classes_lst)
}

id2label = {
    idx: class_name
    for idx, class_name in enumerate(classes_lst)
}

df['sentiment'] = df['sentiment'].apply(lambda x: label2id[x])

train_df, temp_df = train_test_split(
    df,
    test_size=0.3,
    random_state=SEED,
    stratify=df['sentiment']
 )
eval_df, test_df = train_test_split(
    temp_df,
    test_size=1/3,
    random_state=SEED,
    stratify=temp_df['sentiment']
)

# Define the datasets to process
datasets = {
    'Train': train_df,
    'Eval': eval_df,
    'Test': test_df
}

# Create subplots
fig, axes = plt.subplots(1, 3, figsize=(20, 6))

for i, (name, current_df) in enumerate(datasets.items()):
    # Calculate sentence lengths
    lengths = current_df['content'].str.len()

    # Calculate statistics
    mean_val = lengths.mean()
    max_val = lengths.max()
    p95 = np.percentile(lengths, 95)
    p99 = np.percentile(lengths, 99)

    # Print statistics
    print(f"--- {name} Dataset Statistics ---")
    print(f"Mean: {mean_val:.2f}")
    print(f"Max: {max_val}")
    print(f"p95: {p95:.2f}")
    print(f"p99: {p99:.2f}\n")

    # Plot histogram on the corresponding axis
    ax = axes[i]
    ax.hist(lengths, bins=50, color='skyblue', edgecolor='black', alpha=0.7)
    ax.axvline(p95, color='red', linestyle='--', linewidth=2, label=f'p95 ({p95:.1f})')
    ax.axvline(p99, color='orange', linestyle='--', linewidth=2, label=f'p99 ({p99:.1f})')

    ax.set_title(f'Distribution of {name} Lengths')
    ax.set_xlabel('Length')
    ax.set_ylabel('Frequency')
    ax.legend()
    ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.show()

labels = np.array(train_df["sentiment"])

unique, counts = np.unique(labels, return_counts=True)

# Using the existing id2label dictionary
labels_str = [id2label[int(l)] for l in unique]
palette = {
    "negative": "#e74c3c",
    "neutral": "#f1c40f",
    "positive": "#2ecc71"
}

plt.figure(figsize=(8, 5))
ax = sns.barplot(x=labels_str, y=counts, hue=labels_str, palette=palette, dodge=False, legend=False)

plt.title("Train Label Distribution")
plt.xlabel("Sentiment")
plt.ylabel("Count")

for i, v in enumerate(counts):
    ax.text(i, v + max(counts)*0.01, str(v), ha='center', fontsize=11)

plt.ylim(0, max(counts)*1.1)
plt.show()

"""# Utils"""

class FinancialNews(Dataset):
    def __init__(self, X, y, tokenizer, max_seq_len):
        self.texts = X
        self.labels = y
        self.tokenizer = tokenizer
        self.max_seq_len = max_seq_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            truncation=True,
            max_length=self.max_seq_len,
            padding=False,
        )

        item = {key: torch.tensor(val, dtype=torch.long)
                for key, val in encoding.items()}

        item["labels"] = torch.tensor(label, dtype=torch.long)

        return item

def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    preds = np.argmax(predictions, axis=1)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="macro",
        zero_division=0
    )

    acc = accuracy_score(labels, preds)

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

def evaluate_model(trainer, eval_dataset, split_name="test", model_name="RNN"):
    predictions, labels, metrics = trainer.predict(eval_dataset)
    preds = np.argmax(predictions, axis=1)

    target_names = [id2label[i] for i in range(len(id2label))]

    print(f"Evaluation on {split_name} set using {model_name}")
    print("Classification Report:")
    print(classification_report(
        labels,
        preds,
        target_names=target_names,
        zero_division=0
    ))

    acc = accuracy_score(labels, preds)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        preds,
        average="macro",
        zero_division=0
    )

    print(f"Accuracy: {acc:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")

    return {
        "accuracy": acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
    }

def plot_loss_curves(history, title='Training and Validation Loss'):
    # Keep only full-epoch logs to align train/eval points cleanly.
    train_epoch_loss = {}
    eval_epoch_loss = {}

    for log in history:
        epoch = log.get('epoch')
        if epoch is None:
            continue

        epoch_float = float(epoch)
        epoch_int = int(round(epoch_float))

        if epoch_int < 1 or abs(epoch_float - epoch_int) > 1e-8:
            continue

        if 'loss' in log and 'eval_loss' not in log:
            train_epoch_loss[epoch_int] = log['loss']
        if 'eval_loss' in log:
            eval_epoch_loss[epoch_int] = log['eval_loss']

    epochs = sorted(set(train_epoch_loss.keys()) & set(eval_epoch_loss.keys()))
    train_loss = [train_epoch_loss[e] for e in epochs]
    eval_loss = [eval_epoch_loss[e] for e in epochs]

    if not epochs:
        raise ValueError('No aligned full-epoch train/eval loss points were found in trainer.state.log_history.')

    plt.figure(figsize=(10, 6))
    plt.plot(epochs, train_loss, 'b', label='Training loss')
    plt.plot(epochs, eval_loss, 'r', label='Validation loss')
    plt.title(title)
    plt.xlabel('Epochs')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)
    plt.show()

def save_local_checkpoint(model, model_name, base_dir='./saved_models', tokenizer=None):
    """Save model locally for later inference without pushing to Hub."""
    save_dir = Path(base_dir) / model_name
    save_dir.mkdir(parents=True, exist_ok=True)

    if hasattr(model, 'save_pretrained'):
        model.save_pretrained(save_dir)
        if tokenizer is not None and hasattr(tokenizer, 'save_pretrained'):
            tokenizer.save_pretrained(save_dir)
        print(f'Saved Hugging Face model to: {save_dir.resolve()}')
        return str(save_dir)

    torch.save(model.state_dict(), save_dir / 'model_state_dict.pt')
    print(f'Saved PyTorch state_dict to: {(save_dir / "model_state_dict.pt").resolve()}')
    return str(save_dir)

sample_df = test_df.sample(n=10, random_state=SEED).reset_index(drop=True)
texts = sample_df["content"].tolist()
sample_df["true_label"] = sample_df["sentiment"].map(id2label)

"""# RNN-based model

## Build tokenizer
"""

tokenizer_dir = './financial_bpe_tokenizer'
os.makedirs(tokenizer_dir, exist_ok=True)

# Initialize BPE tokenizer with BERT-style subword prefix
raw_tokenizer = Tokenizer(models.BPE(unk_token='<unk>', continuing_subword_prefix='##'))
raw_tokenizer.pre_tokenizer = pre_tokenizers.Whitespace()

bpe_trainer = trainers.BpeTrainer(
    vocab_size=15000,
    special_tokens=['<pad>', '<unk>'],
    continuing_subword_prefix='##'
)

# Train from the content iterator
raw_tokenizer.train_from_iterator(train_df['content'].tolist(), trainer=bpe_trainer)
raw_tokenizer.save(f'{tokenizer_dir}/tokenizer.json')

# Wrap with Transformers for use in model training
hf_fast_tokenizer = PreTrainedTokenizerFast(
    tokenizer_file=f'{tokenizer_dir}/tokenizer.json',
    unk_token='<unk>',
    pad_token='<pad>'
)
hf_fast_tokenizer.save_pretrained(tokenizer_dir)

rnn_tokenizer = AutoTokenizer.from_pretrained(tokenizer_dir, use_fast=True)
vocab_size = rnn_tokenizer.vocab_size
pad_token_id = rnn_tokenizer.pad_token_id

vocab_size

"""## Prepare dataset for training"""

rnn_train_dataset = FinancialNews(
    train_df['content'].tolist(),
    train_df['sentiment'].tolist(),
    tokenizer=rnn_tokenizer,
    max_seq_len=MAX_RNN_LEN,
)
rnn_eval_dataset = FinancialNews(
    eval_df['content'].tolist(),
    eval_df['sentiment'].tolist(),
    tokenizer=rnn_tokenizer,
    max_seq_len=MAX_RNN_LEN,
)
rnn_test_dataset = FinancialNews(
    test_df['content'].tolist(),
    test_df['sentiment'].tolist(),
    tokenizer=rnn_tokenizer,
    max_seq_len=MAX_RNN_LEN,
)

print(f'Train size: {len(rnn_train_dataset)}, Eval size: {len(rnn_eval_dataset)}, Test size: {len(rnn_test_dataset)}')

"""## RNN

### Model definition
"""

class RNNSequenceClassifierConfig(PretrainedConfig):
    model_type = "rnn-sequence-classifier"

    def __init__(
        self,
        vocab_size=5000,
        embedding_dim=128,
        hidden_dim=256,
        num_labels=3,
        num_layers=2,
        dropout=0.3,
        fc_dim=128,
        pad_token_id=0,
        id2label=None,
        label2id=None,
        **kwargs
    ):
        super().__init__(
            pad_token_id=pad_token_id,
            id2label=id2label,
            label2id=label2id,
            **kwargs
        )

        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.num_labels = num_labels
        self.num_layers = num_layers
        self.dropout = dropout
        self.fc_dim = fc_dim

class RNNForSequenceClassification(PreTrainedModel):
    config_class = RNNSequenceClassifierConfig

    def __init__(self, config):
        super().__init__(config)

        self.embedding = nn.Embedding(
            config.vocab_size,
            config.embedding_dim,
            padding_idx=config.pad_token_id
        )

        self.rnn = nn.RNN(
            input_size=config.embedding_dim,
            hidden_size=config.hidden_dim,
            num_layers=config.num_layers,
            batch_first=True
        )

        self.norm = nn.LayerNorm(config.hidden_dim)
        self.dropout = nn.Dropout(config.dropout)

        self.classifier = nn.Sequential(
            nn.Linear(config.hidden_dim, config.fc_dim),
            nn.SiLU(),
            nn.Dropout(config.dropout),
            nn.Linear(config.fc_dim, config.num_labels)
        )

        self.post_init()

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        labels=None,
        **kwargs
    ):
        x = self.embedding(input_ids)
        x = self.dropout(x)

        outputs, _ = self.rnn(x)

        if attention_mask is not None:
            mask = attention_mask.unsqueeze(-1).float()
            pooled = (outputs * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1e-8)
        else:
            pooled = outputs.mean(dim=1)

        pooled = self.norm(pooled)
        pooled = self.dropout(pooled)

        logits = self.classifier(pooled)

        loss = None
        if labels is not None:
            loss = F.cross_entropy(logits, labels)

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits
        )

import sys
from pathlib import Path

dummy_file = "/tmp/notebook.py"
Path(dummy_file).write_text("# dummy notebook file\n", encoding="utf-8")

sys.modules["__main__"].__file__ = dummy_file

rnn_config = RNNSequenceClassifierConfig(
    vocab_size=rnn_tokenizer.vocab_size,
    embedding_dim=128,
    hidden_dim=256,
    num_labels=3,
    num_layers=2,
    dropout=0.3,
    fc_dim=128,
    pad_token_id=rnn_tokenizer.pad_token_id,
    id2label=id2label,
    label2id=label2id
)
rnn_model = RNNForSequenceClassification(rnn_config)

summary(rnn_model, input_size=(1, 10), dtypes=[torch.long])

"""### Training"""

rnn_training_args = TrainingArguments(
    output_dir='rnn_results',
    num_train_epochs=100,
    learning_rate=1e-4,
    warmup_ratio=0.1,
    weight_decay=0.01,

    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,

    logging_strategy='epoch',
    logging_first_step=True,
    eval_strategy='epoch',
    save_strategy='epoch',
    save_total_limit=3,

    report_to='none',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    seed=SEED,
)

rnn_trainer = Trainer(
    model=rnn_model,
    args=rnn_training_args,
    train_dataset=rnn_train_dataset,
    eval_dataset=rnn_eval_dataset,
    data_collator=DataCollatorWithPadding(tokenizer=rnn_tokenizer),
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=15)]
)

rnn_train_result = rnn_trainer.train()
print('Train result:', rnn_train_result)

history = rnn_trainer.state.log_history
plot_loss_curves(history, title='Training and Validation Loss (RNN)')

"""### Evaluate"""

rnn_result = evaluate_model(rnn_trainer, rnn_test_dataset, split_name="test", model_name="RNN")

"""### Inference"""

rnn_pipe = pipeline(
    "text-classification",
    model=rnn_model,
    tokenizer=rnn_tokenizer,
)
preds = rnn_pipe(
    texts,
    truncation=True,
    max_length=MAX_RNN_LEN,
)
rnn_df = sample_df.copy()
rnn_df["pred_label"] = [p["label"] for p in preds]
rnn_df["pred_score"] = [p["score"] for p in preds]
rnn_df[["true_label", "pred_label", "pred_score", "content"]]
display(rnn_df)

"""## LSTM

### Model definition
"""

class LSTMSequenceClassifierConfig(PretrainedConfig):
    model_type = "lstm-sequence-classifier"

    def __init__(
        self,
        vocab_size=5000,
        embedding_dim=128,
        hidden_dim=256,
        num_labels=3,
        num_layers=2,
        dropout=0.3,
        bidirectional=True,
        fc_dim=128,
        pad_token_id=0,
        id2label=None,
        label2id=None,
        **kwargs
    ):
        super().__init__(
            pad_token_id=pad_token_id,
            id2label=id2label,
            label2id=label2id,
            **kwargs
        )

        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.num_labels = num_labels
        self.num_layers = num_layers
        self.dropout = dropout
        self.bidirectional = bidirectional
        self.fc_dim = fc_dim

class LSTMForSequenceClassification(PreTrainedModel):
    config_class = LSTMSequenceClassifierConfig

    def __init__(self, config):
        super().__init__(config)

        self.embedding = nn.Embedding(
            config.vocab_size,
            config.embedding_dim,
            padding_idx=config.pad_token_id
        )

        rnn_dropout = config.dropout if config.num_layers > 1 else 0.0

        self.lstm = nn.LSTM(
            input_size=config.embedding_dim,
            hidden_size=config.hidden_dim,
            num_layers=config.num_layers,
            batch_first=True,
            dropout=rnn_dropout,
            bidirectional=config.bidirectional
        )

        hidden_dim = config.hidden_dim * 2 if config.bidirectional else config.hidden_dim

        self.norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(config.dropout)

        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, config.fc_dim),
            nn.SiLU(),
            nn.Dropout(config.dropout),
            nn.Linear(config.fc_dim, config.num_labels)
        )

        self.post_init()

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        x = self.embedding(input_ids)
        x = self.dropout(x)

        outputs, _ = self.lstm(x)

        if attention_mask is not None:
            mask = attention_mask.unsqueeze(-1).float()
            pooled = (outputs * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1e-8)
        else:
            pooled = outputs.mean(dim=1)

        pooled = self.norm(pooled)
        pooled = self.dropout(pooled)

        logits = self.classifier(pooled)

        loss = None
        if labels is not None:
            loss = F.cross_entropy(logits, labels)

        return SequenceClassifierOutput(loss=loss, logits=logits)

lstm_config = LSTMSequenceClassifierConfig(
    vocab_size=rnn_tokenizer.vocab_size,
    embedding_dim=128,
    hidden_dim=256,
    num_labels=3,
    num_layers=2,
    dropout=0.3,
    fc_dim=128,
    pad_token_id=rnn_tokenizer.pad_token_id,
    id2label=id2label,
    label2id=label2id
)
lstm_model = LSTMForSequenceClassification(lstm_config)

summary(lstm_model, input_size=(1, 10), dtypes=[torch.long])

"""### Training"""

lstm_training_args = TrainingArguments(
    output_dir='lstm_results',
    num_train_epochs=100,
    learning_rate=5e-4,
    warmup_ratio=0.1,
    weight_decay=0.01,

    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,

    logging_strategy='epoch',
    logging_first_step=True,
    eval_strategy='epoch',
    save_strategy='epoch',
    save_total_limit=3,

    report_to='none',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    seed=SEED,
)

lstm_trainer = Trainer(
    model=lstm_model,
    args=lstm_training_args,
    train_dataset=rnn_train_dataset,
    eval_dataset=rnn_eval_dataset,
    data_collator=DataCollatorWithPadding(tokenizer=rnn_tokenizer),
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=15)]
)

lstm_train_result = lstm_trainer.train()
print('Train result:', lstm_train_result)

history = lstm_trainer.state.log_history
plot_loss_curves(history, title='Training and Validation Loss (LSTM)')

"""### Evaluate"""

lstm_result = evaluate_model(
    lstm_trainer,
    rnn_test_dataset,
    split_name="test",
    model_name="LSTM"
)

"""### Inference"""

lstm_pipe = pipeline(
    "text-classification",
    model=lstm_model,
    tokenizer=rnn_tokenizer,
)
preds = lstm_pipe(
    texts,
    truncation=True,
    max_length=MAX_RNN_LEN,
)
lstm_df = sample_df.copy()
lstm_df["pred_label"] = [p["label"] for p in preds]
lstm_df["pred_score"] = [p["score"] for p in preds]
lstm_df[["true_label", "pred_label", "pred_score", "content"]]
display(lstm_df)

"""## GRU

### Model definition
"""

class GRUSequenceClassifierConfig(PretrainedConfig):
    model_type = "gru-sequence-classifier"

    def __init__(
        self,
        vocab_size=5000,
        embedding_dim=128,
        hidden_dim=256,
        num_labels=3,
        num_layers=2,
        dropout=0.3,
        bidirectional=True,
        fc_dim=128,
        pad_token_id=0,
        id2label=None,
        label2id=None,
        **kwargs
    ):
        super().__init__(
            pad_token_id=pad_token_id,
            id2label=id2label,
            label2id=label2id,
            **kwargs
        )

        self.vocab_size = vocab_size
        self.embedding_dim = embedding_dim
        self.hidden_dim = hidden_dim
        self.num_labels = num_labels
        self.num_layers = num_layers
        self.dropout = dropout
        self.bidirectional = bidirectional
        self.fc_dim = fc_dim

class GRUForSequenceClassification(PreTrainedModel):
    config_class = GRUSequenceClassifierConfig

    def __init__(self, config):
        super().__init__(config)

        self.embedding = nn.Embedding(
            config.vocab_size,
            config.embedding_dim,
            padding_idx=config.pad_token_id
        )

        rnn_dropout = config.dropout if config.num_layers > 1 else 0.0

        self.gru = nn.GRU(
            input_size=config.embedding_dim,
            hidden_size=config.hidden_dim,
            num_layers=config.num_layers,
            batch_first=True,
            dropout=rnn_dropout,
            bidirectional=config.bidirectional
        )

        hidden_dim = config.hidden_dim * 2 if config.bidirectional else config.hidden_dim

        self.norm = nn.LayerNorm(hidden_dim)
        self.dropout = nn.Dropout(config.dropout)

        self.classifier = nn.Sequential(
            nn.Linear(hidden_dim, config.fc_dim),
            nn.SiLU(),
            nn.Dropout(config.dropout),
            nn.Linear(config.fc_dim, config.num_labels)
        )

        self.post_init()

    def forward(self, input_ids=None, attention_mask=None, labels=None, **kwargs):
        x = self.embedding(input_ids)
        x = self.dropout(x)

        outputs, _ = self.gru(x)

        if attention_mask is not None:
            mask = attention_mask.unsqueeze(-1).float()
            pooled = (outputs * mask).sum(dim=1) / mask.sum(dim=1).clamp(min=1e-8)
        else:
            pooled = outputs.mean(dim=1)

        pooled = self.norm(pooled)
        pooled = self.dropout(pooled)

        logits = self.classifier(pooled)

        loss = None
        if labels is not None:
            loss = F.cross_entropy(logits, labels)

        return SequenceClassifierOutput(loss=loss, logits=logits)

gru_config = GRUSequenceClassifierConfig(
    vocab_size=rnn_tokenizer.vocab_size,
    embedding_dim=128,
    hidden_dim=256,
    num_labels=3,
    num_layers=2,
    dropout=0.3,
    fc_dim=128,
    pad_token_id=rnn_tokenizer.pad_token_id,
    id2label=id2label,
    label2id=label2id
)
gru_model = GRUForSequenceClassification(gru_config)

"""### Training"""

gru_training_args = TrainingArguments(
    output_dir='gru_results',
    num_train_epochs=100,
    learning_rate=5e-4,
    warmup_ratio=0.1,
    weight_decay=0.01,

    per_device_train_batch_size=128,
    per_device_eval_batch_size=128,

    logging_strategy='epoch',
    logging_first_step=True,
    eval_strategy='epoch',
    save_strategy='epoch',
    save_total_limit=3,

    report_to='none',
    load_best_model_at_end=True,
    metric_for_best_model='f1',
    greater_is_better=True,
    seed=SEED,
)

gru_trainer = Trainer(
    model=gru_model,
    args=gru_training_args,
    train_dataset=rnn_train_dataset,
    eval_dataset=rnn_eval_dataset,
    data_collator=DataCollatorWithPadding(tokenizer=rnn_tokenizer),
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=15)]
)

gru_train_result = gru_trainer.train()
print('Train result:', gru_train_result)

history = gru_trainer.state.log_history
plot_loss_curves(history, title='Training and Validation Loss (GRU)')

"""### Evaluate"""

gru_result = evaluate_model(
    gru_trainer,
    rnn_test_dataset,
    split_name="test",
    model_name="GRU"
)

"""### Inference"""

gru_pipe = pipeline(
    "text-classification",
    model=gru_model,
    tokenizer=rnn_tokenizer,
)
preds = gru_pipe(
    texts,
    truncation=True,
    max_length=MAX_RNN_LEN,
)
gru_df = sample_df.copy()
gru_df["pred_label"] = [p["label"] for p in preds]
gru_df["pred_score"] = [p["score"] for p in preds]
gru_df[["true_label", "pred_label", "pred_score", "content"]]
display(gru_df)

"""# BERT-based model

## MiniLM

### Model defination & Tokenizer
"""

minilm_tokenizer = AutoTokenizer.from_pretrained("sentence-transformers/all-MiniLM-L12-v2")
minilm_model = AutoModelForSequenceClassification.from_pretrained(
    "sentence-transformers/all-MiniLM-L12-v2",
    num_labels=n_classes,
    id2label=id2label,
    label2id=label2id
)

minilm_train_dataset = FinancialNews(
    train_df['content'].tolist(),
    train_df['sentiment'].tolist(),
    tokenizer=minilm_tokenizer,
    max_seq_len=MAX_BERT_LEN,
)
minilm_eval_dataset = FinancialNews(
    eval_df['content'].tolist(),
    eval_df['sentiment'].tolist(),
    tokenizer=minilm_tokenizer,
    max_seq_len=MAX_BERT_LEN,
)
minilm_test_dataset = FinancialNews(
    test_df['content'].tolist(),
    test_df['sentiment'].tolist(),
    tokenizer=minilm_tokenizer,
    max_seq_len=MAX_BERT_LEN,
)

"""### Training"""

minilm_training_args = TrainingArguments(
    output_dir='minilm_results',
    num_train_epochs=10,
    learning_rate=1e-4,

    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,

    logging_strategy='epoch',
    logging_first_step=True,
    eval_strategy='epoch',
    save_strategy='epoch',
    save_total_limit=3,

    report_to='none',
    load_best_model_at_end=True,
    metric_for_best_model='eval_f1',
    greater_is_better=True,
    seed=SEED,
)

minilm_trainer = Trainer(
    model=minilm_model,
    args=minilm_training_args,
    train_dataset=minilm_train_dataset,
    eval_dataset=minilm_eval_dataset,
    data_collator=DataCollatorWithPadding(tokenizer=minilm_tokenizer),
    compute_metrics=compute_metrics,
)

minilm_train_result = minilm_trainer.train()
print('Train result:', minilm_train_result)

history = minilm_trainer.state.log_history
plot_loss_curves(history, title='Training and Validation Loss (MiniLM)')

"""### Evaluate"""

minilm_result = evaluate_model(
    minilm_trainer,
    minilm_test_dataset,
    split_name="test",
    model_name="MiniLM"
)

"""### Inference"""

minilm_pipe = pipeline(
    "text-classification",
    model=minilm_model,
    tokenizer=minilm_tokenizer,
)
preds = minilm_pipe(
    texts,
    truncation=True,
    max_length=MAX_BERT_LEN,
)
minilm_df = sample_df.copy()
minilm_df["pred_label"] = [p["label"] for p in preds]
minilm_df["pred_score"] = [p["score"] for p in preds]
minilm_df[["true_label", "pred_label", "pred_score", "content"]]
display(minilm_df)

"""# Benchmark"""

# Prepare data
models = ['RNN', 'LSTM', 'GRU', 'MiniLM']
results = [rnn_result, lstm_result, gru_result, minilm_result]
metrics = ['accuracy', 'precision', 'recall', 'f1']

x = np.arange(len(metrics))  # the label locations
width = 0.2  # the width of the bars

fig, ax = plt.subplots(figsize=(12, 6))

for i, (model_name, res) in enumerate(zip(models, results)):
    values = [res[m] for m in metrics]
    offset = (i - 1.5) * width
    bars = ax.bar(x + offset, values, width, label=model_name)

    # Add text annotations on top of the bars
    for bar in bars:
        yval = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.4f}', ha='center', va='bottom', fontsize=9)

# Add some text for labels, title and custom x-axis tick labels, etc.
ax.set_ylabel('Scores')
ax.set_title('Performance Comparison of 4 Models')
ax.set_xticks(x)
ax.set_xticklabels([m.capitalize() for m in metrics])
ax.set_ylim(0, 1.1)  # Set y-limit slightly above 1 to make room for text
ax.legend(loc='lower center', bbox_to_anchor=(0.5, -0.2), ncol=4)
plt.rcParams["font.size"] = 12
plt.rcParams["axes.titlesize"] = 14
plt.tight_layout()
plt.show()